export {
  APEX,
  A,
  AAAA,
  CNAME,
  TXT,
  MX,
  SRV,
  CAA,
  CAA_ISSUE,
  CAA_ISSUEWILD,
  CAA_IODEF,
  NS,
  DS,
  HTTPS,
  SVCB,
  type RecordOptions,
  type RecordSpec,
  type RecordType,
  type ARecordSpec,
  type AaaaRecordSpec,
  type CnameRecordSpec,
  type TxtRecordSpec,
  type MxRecordSpec,
  type SrvRecordSpec,
  type CaaRecordSpec,
  type NsRecordSpec,
  type DsRecordSpec,
  type HttpsRecordSpec,
  type SvcbRecordSpec,
} from "./zone-dsl.js";
export {
  zoneRecords,
  type IZoneRecordsBuilder,
  type ZoneRecordsBuilderResult,
} from "./zone-records.js";
